#!/bin/bash
#PBS -q gen3.q
#PBS -l nodes=1
#PBS -l mem=32gb
#PBS -l walltime=01:00:00
#PBS -N optimize_dibecp
#PBS -m abe
#PBS -M cgb31826

export PBS_O_WORKDIR=/home/vulcan/cgb31826/git/Dimagnesocene
cd $PBS_O_WORKDIR

module load psi4-master-intel-16.0.1-avducsgnonqrcpftiesq432gagal6y7r

psi4 -i /home/vulcan/cgb31826/git/Dimagnesocene/in/diberylocene.in -o /home/vulcan/cgb31826/git/Dimagnesocene/out/diberylocene.out -n 8
